book_repository/blueprints/author/__init__.py
from flask import Blueprint, request, render_template
from flask_login import login_required

from ...services.author import get_current_user_all_authors_paginator, get_author_name
from ...services.book import get_current_user_books_per_author_paginator
from ...login_manager.permissions import view_author_permission


author = Blueprint(
	"author",
	__name__,
	template_folder="templates",
	url_prefix="/author"
)


@author.route("/")
@login_required
def all_authors():
	page = request.args.get("page", 1, type=int)
	page_size = request.args.get("page_size", 10, type=int)
	search = request.args.get("q", "", type=str)

	search = None if search == "" else search

	paginator = get_current_user_all_authors_paginator(page, page_size, search)

	extra_params = {
		"q": search
	}

	return render_template("authors_list.html", paginator=paginator, extra_params=extra_params)


@author.route("/<int:author_id>/details")
@view_author_permission.require()
def author_details(author_id):
	page = request.args.get("page", 1, type=int)
	page_size = request.args.get("page_size", 8, type=int)

	paginator = get_current_user_books_per_author_paginator(author_id, page, page_size)
	subtitle = get_author_name(author_id).title()

	extra_params = {
		"author_id": author_id,
	}

	return render_template(
		"paginated_bookshelf.html", paginator=paginator,
		selection_title=subtitle, extra_params=extra_params)

book_repository/blueprints/book/__init__.py
from flask import Blueprint, abort, render_template, make_response, redirect
from flask_login import current_user, login_required
import os
import mimetypes

from ...login_manager.permissions import admin_permission, view_book_permission
from ...services.book import get_book_by_id, get_book_file_path, get_book_cover_path
from ...services.book_permission import get_user_book_permission_type
from ...models.app.book_permission import BookPermissionType
from ...file_provider import file_provider


book = Blueprint(
	"book",
	__name__,
	template_folder="templates",
	url_prefix="/book"
)


@book.route("/<int:book_id>/details")
@login_required
def book_details(book_id: int):
	if admin_permission.can():
		permission_level = BookPermissionType.EDIT
	else:
		permission_level = get_user_book_permission_type(current_user.id, book_id)

	if not permission_level:
		abort(403)

	book_data = get_book_by_id(book_id)
	return render_template(
		"book_details.html",
		book=book_data
	)


@book.route("/<int:book_id>/cover")
@view_book_permission.require()
def book_cover(book_id):
	path = get_book_cover_path(book_id)

	if not path:
		return redirect("https://bulma.io/images/placeholders/256x256.png")

	file = file_provider.load(path)

	response = make_response(file)
	response.headers.set("Content-Type", "image/jpeg")
	response.headers.set("Content-Disposition", "inline")
	return response


@book.route("/<int:book_id>/version/<string:version>")
@view_book_permission.require()
def book_file(book_id: int, version: str):
	path = get_book_file_path(book_id, version)

	if not path:
		abort(404)

	file = file_provider.load(path)
	mimetype = mimetypes.types_map.get(".{}".format(version.lower()), "application/octet-stream")

	response = make_response(file)
	response.headers.set("Content-Type", mimetype)
	response.headers.set("Content-Disposition", "attachment", filename=os.path.basename(path))
	return response

book_repository/blueprints/dashboard/__init__.py
from flask import Blueprint, render_template
from flask_login import login_required

from ...login_manager.permissions import normal_permission
from ...services.book import get_current_user_latest_books

dashboard = Blueprint(
	"dashboard",
	__name__,
	template_folder="templates"
)


@dashboard.route("/")
@login_required
@normal_permission.require()
def index():
	latest_books = get_current_user_latest_books(8)
	return render_template("index.html", latest_books=latest_books)

book_repository/blueprints/language/__init__.py
from flask import Blueprint, request, render_template
from flask_login import login_required

from ...services.language import get_current_user_language_paginator, get_language_name
from ...login_manager.permissions import view_language_permission
from ...services.book import get_current_user_book_per_language_paginator

language = Blueprint(
	"language",
	__name__,
	template_folder="templates",
	url_prefix="/lang"
)


@language.route("/")
@login_required
def all_languages():
	page = request.args.get("page", 1, type=int)
	page_size = request.args.get("page_size", 10, type=int)

	paginator = get_current_user_language_paginator(page, page_size)
	return render_template("languages_list.html", paginator=paginator)


@language.route("/<int:language_id>/details")
@view_language_permission.require()
def language_details(language_id):
	page = request.args.get("page", 1, type=int)
	page_size = request.args.get("page_size", 8, type=int)

	paginator = get_current_user_book_per_language_paginator(language_id, page, page_size)
	subtitle = get_language_name(language_id).upper()

	extra_params = {
		"language_id": language_id,
	}

	return render_template(
		"paginated_bookshelf.html", paginator=paginator,
		selection_title=subtitle, extra_params=extra_params)

book_repository/templates/form_helpers.html
{% macro render_field(field) %}
	<div class="field">
		<label class="label">
			{{ field.label }}
		</label>
		<div class="control">
			{{ field(class_="input",**kwargs) | safe }}
		</div>
		{% for error in field.errors %}
			<p class="help is-danger">
				{{ error }}
			</p>
		{% endfor %}
	</div>
{% endmacro %}

book_repository/templates/fullscreen.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-CCompatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Book repository{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
	{% block head_bottom %}
	{% endblock %}
</head>
<body>
	{% block body %}
	{% endblock %}
	{% block script %}
	{% endblock %}
</body>
</html>

book_repository/templates/master.html
{% extends "fullscreen.html" %}

{% block head_bottom %}
	<link rel="stylesheet" href="{{ url_for("static", filename="css/main.css") }}">
	{% block extra_css %}
	{% endblock %}
{% endblock %}

{% block body %}
	<nav id="main-sidebar" class="sidebar">
		<section class="sidebar-section">
			<ul class="sidebar-section-list">
				<li class="mb-4">
					<a href="{{ url_for("dashboard.index") }}" class="is-size-4">
						Book repository
					</a>
				</li>
				<li class="mb-2">
					<a href="{{ url_for("author.all_authors") }}" class="is-size-6">
						Authors
					</a>
				</li>
				<li class="mb-2">
					<a href="{{ url_for("language.all_languages") }}" class="is-size-6">
						Languages
					</a>
				</li>
				<li>
					<a href="{{ url_for("publisher.all_publishers") }}" class="is-size-6">
						Publishers
					</a>
				</li>
			</ul>
		</section>
		<section class="sidebar-section">
			<ul class="sidebar-section-list">
				<li class="mb-3">
					<a href="{{ url_for("settings.profile") }}" class="is-size-6 log_out">
						<ion-icon name="settings-outline">
						</ion-icon>
						<span>
							Settings
						</span>
					</a>
				</li>
				<li>
					<a href="{{ url_for("auth.logout") }}" class="is-size-7 log_out">
						<ion-icon name="exit-outline">
						</ion-icon>
						<span>
							Log out
						</span>
					</a>
				</li>
			</ul>
		</section>
	</nav>
	<div id="main-site" class="has-navbar-fixed-top">
		<header>
			<nav class="navbar is-info is-fixed-top" id="menu">
				<div class="navbar-brand">
					<a role="button" class="navbar-item btn-burger toggle-button" aria-label="menu" aria-expanded="false">
					  <span aria-hidden="true"></span>
					  <span aria-hidden="true"></span>
					  <span aria-hidden="true"></span>
					</a>
					<a class="navbar-item" href="{{ url_for("dashboard.index") }}">
						Book repository
					</a>
				</div>
			</nav>
		</header>
		<main id="content">
				{% block content %}
				{% endblock %}
			</main>
	</div>
{% endblock %}

{% block script %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/slideout/1.0.1/slideout.min.js"></script>
	<script>
		var slideout = new Slideout({
			"panel": document.getElementById("main-site"),
			"menu": document.getElementById("main-sidebar"),
			"padding":256,
			"tolerance": 70
		});
		document.querySelector('.toggle-button').addEventListener('click', function() {
			slideout.toggle();
		});
	</script>
	<script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
	{% block extra_js %}
	{% endblock %}
{% endblock %}

book_repository/templates/paginated_bookshelf.html
{% extends "master.html" %}
{% from "pagination.html" import render_pagination, pagination_js %}

{% block extra_css %}
	<style>
		.bookshelf
		{
			display: grid;
			justify-content: space-evenly;
			grid-template-columns: auto;
			grid-gap: 10px;
			grid-row-gap: 20px;
			padding-right: 10px;
			padding-left: 10px;
		}

		.bookshelf > .book
		{
			list-style-type: none;
			width: 60vw;
			height: 80vw;
			-webkit-box-shadow: 0 0 12px rgba(0,0,0,0.5);
			-moz-box-shadow: 0 0 12px rgba(0,0,0,0.5);
			box-shadow: 0 0 12px rgba(0,0,0,0.5);
			position: relative;
			overflow: hidden;
		}

		@media(min-width: 768px)
		{
			.bookshelf
			{
				grid-template-columns: repeat(4, auto);
			}

			.bookshelf > .book
			{
				width: 21vw;
				height: 28vw;
			}
		}

		@media(min-width: 1024px)
		{
			.bookshelf > .book
			{
				width: 12vw;
				height: 16vw;
			}
		}

		.book > img
		{
			height: 100%;
			width: 100%;
			object-fit: fill;
		}

		.book-overlay-top:after
		{
			content: "";
			display: block;
			position: absolute;
			bottom: -1px;
			left: 45%;
			width: 10%;
			z-index: 1;
			border-bottom: 3px solid #fff;
		}

		.book-overlay-top, .book-overlay-bottom
		{
			position: absolute;
			background-color: #000;
			text-align: center;
			width: 100%;
			overflow: hidden;
			height: 50%;
			color: #fff;
			opacity: 0.75;
			padding-left: 1em;
			padding-right: 1em;

			transition: top 0.2s ease-out, bottom 0.2s ease-out;
		}

		.book-overlay-top
		{
			top: -50%;
			display: grid;
			align-content: end;
			padding-bottom: 0.75rem;
		}


		.book-overlay-bottom
		{
			bottom: -50%;
			display: flex;
			align-content: start;
			justify-content: center;
			padding-top: 1rem;
			grid-column-gap: 10px;
		}

		.book:hover > .book-overlay-top, .book:active > .book-overlay-top
		{
			top: 0;
		}

		.book:hover > .book-overlay-bottom, .book:active > .book-overlay-bottom
		{
			bottom: 0;
		}

		.book-action
		{
			color: rgb(255, 255, 255);
		}

		.book-action > ion-icon
		{
			font-weight: bold;
			font-size: x-large;
		}

		.book-title
		{
			position: relative;
			word-break: normal;
			overflow: hidden;
			text-overflow:  ellipsis;
			font-size-adjust: 0.5;
		}


	</style>
{% endblock %}

{% block content %}
	<section class="box">
		<h3 class="is-size-3 ml-4 mb-2">
			{{ selection_title }}
		</h3>
		<ul class="bookshelf pb-5">
		{% for book in paginator.items %}
			<li class="book">
				<div class="book-overlay-top">
					<div class="book-title">
						<h4>
						{{ book.title }}
						</h4>
					</div>
				</div>
				<img src="{{ url_for("book.book_cover", book_id=book.id) }}" alt="{{ book.title }}">
				<div class="book-overlay-bottom">
					{% if "EPUB" in book.data | map(attribute="format") | map("upper") %}
					<a href="{{url_for("epub_reader.read", book_id=book.id)}}" class="book-action">
						<ion-icon name="book-outline">
						</ion-icon>
					</a>
					{% endif %}
					<a href="{{ url_for("book.book_details", book_id=book.id) }}" class="book-action">
						<ion-icon name="information-circle-outline">
						</ion-icon>
					</a>
				</div>
			</li>
		{% endfor %}
		</ul>
		{{ render_pagination(request.endpoint, paginator, extra_params, sizes=[4, 8, 12, 16]) }}
	</section>
{% endblock %}

{% block extra_js %}
	{{ pagination_js() }}
{% endblock %}

book_repository/templates/pagination.html
{% macro pagination_link(endpoint, page, page_size, class, content, label, extra=None) %}
			{% if extra %}
				<a class="{{class}}" aria-label="{{ label }}"
			        href="{{ url_for(endpoint, page=page, page_size=page_size, **extra) }}">
					{{ content }}
				</a>
			{% else %}
				<a class="{{class}}" aria-label="{{ label }}"
			        href="{{ url_for(endpoint, page=page, page_size=page_size) }}">
					{{ content }}
				</a>
			{% endif %}
{% endmacro %}

{% macro render_pagination(endpoint, pagination, extra, sizes=[5, 10, 15, 20, 25]) %}
	{% if pagination.total > pagination.per_page %}
	<nav class="pagination is-centered" role="navigation" aria-label="pagination">
		{% if pagination.has_prev %}
			{{ pagination_link(endpoint, pagination.prev_num, pagination.per_page, "pagination-previous", "Previous", "Previous", extra) }}
		{% endif %}
		<ul class="pagination-list">
			{% for page in pagination.iter_pages(left_edge=1, left_current=2, right_current=3, right_edge=1) %}
				<li>
				{% if page %}
					{% if page == pagination.page %}
						<span class="pagination-link is-current">
							{{ page }}
						</span>
					{% else %}
						{{ pagination_link(endpoint, page, pagination.per_page, "pagination-link", page, "Goto page {}".format(page), extra) }}
					{% endif %}
				{% else %}
						<span class="pagination-ellipsis">
							&hellip;
						</span>
				{% endif %}
				</li>
			{% endfor %}
		</ul>
		{% if pagination.has_next %}
			{{ pagination_link(endpoint, pagination.next_num, pagination.per_page, "pagination-next", "Next", "Next", extra) }}
		{% endif %}
		<!-- page size select -->
		<div class="dropdown is-right size_select is-up">
			<div class="dropdown-trigger">
				<button class="button" aria-haspopup="true" aria-controls="download-menu">
					{{ pagination.per_page }} items
				</button>
			</div>
			<div class="dropdown-menu" id="download-menu" role="menu">
				<div class="dropdown-content">
					<span class="dropdown-item">
						{{ pagination.per_page }} items
					</span>
					{% for page_size in sizes %}
						{% if pagination.per_page != page_size %}
							{{ pagination_link(endpoint, 1, page_size, "dropdown-item", "{} items".format(page_size), "", extra) }}
						{% endif %}
					{% endfor %}
				</div>
			</div>
		</div>
	</nav>
	{% endif %}
{% endmacro %}

{% macro pagination_js() %}
	<script>
		(function() {
			const paginator_dropdown = document.querySelectorAll(".pagination .size_select");
			paginator_dropdown.forEach((elem) => {
				elem.addEventListener("click", (event) => {
					event.stopPropagation();
					elem.classList.toggle("is-active");
				})
			});
		}());
	</script>
{% endmacro %}