book_repository/blueprints/author/__init__.py
from flask import Blueprint, request, render_template
from flask_login import login_required

from ...services.author import get_current_user_all_authors_paginator, get_author_name
from ...services.book import get_current_user_books_per_author_paginator
from ...login_manager.permissions import view_author_permission


author = Blueprint(
	"author",
	__name__,
	template_folder="templates",
	url_prefix="/author"
)


@author.route("/")
@login_required
def all_authors():
	page = request.args.get("page", 1, type=int)
	page_size = request.args.get("page_size", 10, type=int)
	search = request.args.get("q", "", type=str)

	search = None if search == "" else search

	paginator = get_current_user_all_authors_paginator(page, page_size, search)

	extra_params = {
		"q": search
	}

	return render_template("authors_list.html", paginator=paginator, extra_params=extra_params)


@author.route("/<int:author_id>/details")
@view_author_permission.require()
def author_details(author_id):
	page = request.args.get("page", 1, type=int)
	page_size = request.args.get("page_size", 8, type=int)

	paginator = get_current_user_books_per_author_paginator(author_id, page, page_size)
	subtitle = get_author_name(author_id).title()

	extra_params = {
		"author_id": author_id,
	}

	return render_template(
		"paginated_bookshelf.html", paginator=paginator,
		selection_title=subtitle, extra_params=extra_params)

book_repository/blueprints/author/templates/authors_list.html
{% extends "master.html" %}
{% from "pagination.html" import render_pagination, pagination_js %}

{% block title %} Authors list{% endblock %}

{% block extra_css %}
	<style>
		.box > .box-header
		{
			display: flex;
			justify-content: space-between;
			align-items: center;
		}
	</style>
{% endblock %}

{% block content %}
	<div class="box">
		<header class="box-header">
			<h3 class="is-size-3">
			Authors
			</h3>
			<form method="GET">
				<input type="hidden" name="page" value="1">
				<input type="hidden" name="page_size" value="{{ paginator.per_page }}">
				<div class="field has-addons">
					<label hidden="hidden" for="author_search">Search author</label>
					<div class="control">
						<input class="input is-small" type="text" name="q" id="author_search">
					</div>
					<div class="control">
						<button type="submit" class="button is-info is-small">
							<ion-icon name="search-outline"></ion-icon>
						</button>
					</div>
				</div>
			</form>
		</header>
		<table class="table is-fullwidth is-stripped is-hoverable">
			<thead>
				<tr>
					<th>
						<abbr title="Position">Pos</abbr>
					</th>
					<th>Author</th>
					<th>Book count</th>
				</tr>
			</thead>
			<tbody>
				{% for author in paginator.items %}
				<tr>
					<th>{{ (paginator.page - 1) * paginator.per_page + loop.index }}</th>
					<td>
						<a href="{{ url_for("author.author_details", author_id=author.id) }}">
							{{ author.name }}
						</a>
					</td>
					<td>{{ author.books | length }}</td>

				</tr>
				{% endfor %}
			</tbody>
		</table>
		{{ render_pagination("author.all_authors", paginator, extra_params) }}
	</div>
{% endblock %}

{% block extra_js %}
	{{ pagination_js() }}
{% endblock %}