book_repository/blueprints/book/__init__.py
from flask import Blueprint, abort, render_template, make_response, redirect
from flask_login import current_user, login_required
import os
import mimetypes

from ...login_manager.permissions import admin_permission, view_book_permission
from ...services.book import get_book_by_id, get_book_file_path, get_book_cover_path
from ...services.book_permission import get_user_book_permission_type
from ...models.app.book_permission import BookPermissionType
from ...file_provider import file_provider


book = Blueprint(
	"book",
	__name__,
	template_folder="templates",
	url_prefix="/book"
)


@book.route("/<int:book_id>/details")
@login_required
def book_details(book_id: int):
	if admin_permission.can():
		permission_level = BookPermissionType.EDIT
	else:
		permission_level = get_user_book_permission_type(current_user.id, book_id)

	if not permission_level:
		abort(403)

	book_data = get_book_by_id(book_id)
	return render_template(
		"book_details.html",
		book=book_data
	)


@book.route("/<int:book_id>/cover")
@view_book_permission.require()
def book_cover(book_id):
	path = get_book_cover_path(book_id)

	if not path:
		return redirect("https://bulma.io/images/placeholders/256x256.png")

	file = file_provider.load(path)

	response = make_response(file)
	response.headers.set("Content-Type", "image/jpeg")
	response.headers.set("Content-Disposition", "inline")
	return response


@book.route("/<int:book_id>/version/<string:version>")
@view_book_permission.require()
def book_file(book_id: int, version: str):
	path = get_book_file_path(book_id, version)

	if not path:
		abort(404)

	file = file_provider.load(path)
	mimetype = mimetypes.types_map.get(".{}".format(version.lower()), "application/octet-stream")

	response = make_response(file)
	response.headers.set("Content-Type", mimetype)
	response.headers.set("Content-Disposition", "attachment", filename=os.path.basename(path))
	return response

book_repository/blueprints/book/templates/book_details.html
{% extends "master.html" %}

{%  macro book_detail(name, value) %}
	<p>
		<span class="book-detail">
			{{ name }}:
		</span>
		<span class="book-detail-value">
			{{ value }}
		</span>
	</p>
{% endmacro %}

{% macro authors_list(authors) %}
	{% for author in authors %}
		<a href="{{ url_for("author.author_details", author_id=author.id) }}" class="tag">
			{{ author.name }}
		</a> {{ "," if not loop.last }}
	{% endfor %}
{% endmacro %}

{% macro languages_list(languages) %}
	{% for language in languages %}
		<a href="{{ url_for("language.language_details", language_id=language.id) }}" class="tag">{{ language.lang_code | upper}}</a> {{ "," if not loop.last }}
	{% endfor %}
{% endmacro %}

{% macro series_list(series, index) %}
	{% for entry in series %}
		<a href="#" class="tags has-addons is-inline">
			<span class="tag">
				{{ entry.name }}
			</span>
			<span class="tag is-info">
				{{ index }}
			</span>
		</a> {{ "," if not loop.last }}
	{% endfor %}
{% endmacro %}

{% macro tags_list(tags) %}
	{% for tag in tags %}
		<span class="tag">{{ tag.name | upper }}</span> {{ "," if not loop.last }}
	{% endfor %}
{% endmacro %}

{% macro publishers_list(publishers) %}
	{% for publisher in publishers %}
		<a href="{{ url_for("publisher.publisher_details", publisher_id = publisher.id) }}" class="tag">{{ publisher.name }}</a> {{ "," if not loop.last }}
	{% endfor %}
{% endmacro %}

{% block extra_css %}
	<style>
		.media-left > .image
		{
			width: 200px
		}

		#content header
		{
			display: flex;
			justify-content: space-between;
		}

		.dropdown-menu
		{
			min-width: unset;
		}
	</style>
{% endblock %}

{% block title %}: {{ book.title | title }}{% endblock %}

{% block content %}
	<div class="box mt-4">
		<article class="media">
			<div class="media-left">
				<figure class="image is-3by4">
					<img src={{ url_for("book.book_cover", book_id=book.id) }} alt="Image">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<header>
						<h3 class="is-size-5">
							{{ book.title }}
						</h3>
						<div class="actions field">
							{% if "EPUB" in book.data | map(attribute="format") | map("upper") %}
							<a href="{{ url_for("epub_reader.read", book_id=book.id) }}" class="button">
								<ion-icon name="book-outline">
								</ion-icon>
							</a>
							{% endif %}
							<div class="dropdown is-right">
								<div class="dropdown-trigger">
									<button class="button" aria-haspopup="true" aria-controls="download-menu">
										<ion-icon name="download-outline">
										</ion-icon>
									</button>
								</div>
								<div class="dropdown-menu" id="download-menu" role="menu">
									<div class="dropdown-content">
										{% for format in book.data | map(attribute="format") | map("upper") %}
										<a class="dropdown-item" href="{{ url_for("book.book_file", book_id=book.id, version=format|lower) }}">
											{{ format | upper }}
										</a>
										{% endfor %}
									</div>
								</div>
							</div>

						</div>
					</header>
					<article class="book-details">
						{{ book_detail("Author", authors_list(book.authors)) }}
						{{ book_detail("Languages", languages_list(book.languages)) }}
						{% if book.series %}
						{{ book_detail("Series", series_list(book.series, book.series_index)) }}
						{% endif %}
						{{ book_detail("Publishers", publishers_list(book.publishers)) }}
						{{ book_detail("Tags", tags_list(book.tags)) }}
						{{ book_detail("Publication date:", book.pubdate.strftime('%Y-%m-%d %H:%M')) }}
						{% if book.comment %}
							<p class="book-detail">Description</p>
							<p>
							{{ book.comment.text | safe }}
							</p>
						{% endif %}
					</article>
				</div>
			</div>
		</article>
	</div>
{% endblock %}

{% block extra_js %}
	<script>
		(function() {
			const download_dropdown = document.querySelector(".actions .dropdown");
			download_dropdown.addEventListener("click", (event) => {
				event.stopPropagation();
				download_dropdown.classList.toggle("is-active");
			})
		}());
	</script>
{% endblock %}